version: '3.8'
services:
  db:
    image: postgres:16
    container_name: artprobe_db
    restart: "no"
    environment:
      POSTGRES_USER: jakob_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: artprobe_db
    ports:
      - '5432:5432'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: